### ISSUE TITLE
Bug ToDo List

### ISSUE THREAD

**Issue by dogukanoksuz** [dogukanoksuz/dogukan.dev#1]
- [x] Safari animation bugs on macOS and iOS latest, should investigate Framer Motion
- [x] On mobile view, search bar not working
- [x] On mobile view, post thumbnails is too small because of Next
- [x] Contact form is not working, should write a SMTP handler on Next
- [x] Add target _blank to external links
